// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Online_Learning.Models.Entities;

public partial class CourseImage
{
    public long ImageId { get; set; }

    public string ImageUrl { get; set; }

    public string CourseId { get; set; }

    public virtual Course Course { get; set; }
}