// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Online_Learning.Models.Entities;

public partial class CourseEnrollment
{
    public string CourseId { get; set; }

    public string UserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public int Status { get; set; }

    public int Progress { get; set; }

    public virtual Course Course { get; set; }

    public virtual User User { get; set; }
}