// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Online_Learning.Models.Entities;

public partial class Function
{
    public long FunctionId { get; set; }

    public string ApiUrl { get; set; }

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}