// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Online_Learning.Models.Entities;

public partial class LessonProgress
{
    public long LessonId { get; set; }

    public string UserId { get; set; }

    public DateTime? CompletedAt { get; set; }

    public bool? IsCompleted { get; set; }

    public virtual Lesson Lesson { get; set; }

    public virtual User User { get; set; }
}