// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Online_Learning.Models.Entities;

public partial class Lesson
{
    public long LessonId { get; set; }

    public long ModuleId { get; set; }

    public int LessonNumber { get; set; }

    public string LessonName { get; set; }

    public string LessonContent { get; set; }

    public string LessonVideo { get; set; }

    public int? Duration { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<LessonProgress> LessonProgresses { get; set; } = new List<LessonProgress>();

    public virtual Module Module { get; set; }
}