// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Online_Learning.Models.Entities;

public partial class Rating
{
    public long RatingId { get; set; }

    public string CourseId { get; set; }

    public string UserId { get; set; }

    public byte Score { get; set; }

    public string ReviewText { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Course Course { get; set; }

    public virtual User User { get; set; }
}