// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Online_Learning.Models.Entities;

public partial class UserAnswer
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	public long UserAnswerId { get; set; }

    public string UserId { get; set; }

    public long OptionId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Option Option { get; set; }

    public virtual User User { get; set; }
}