// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Online_Learning.Models.Entities;

public partial class UserQuizResult
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	public long UserQuizResultId { get; set; }

    public string UserId { get; set; }

    public long QuizId { get; set; }

    public decimal Score { get; set; }

    public int CorrectAnswers { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Quiz Quiz { get; set; }

    public virtual User User { get; set; }
}